# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import Message as google___protobuf___message___Message

from typing import (
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    Union as typing___Union,
    cast as typing___cast,
)

from typing_extensions import Literal as typing_extensions___Literal

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode

class JobSpec(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ...  # type: typing___Text
    num_tasks = ...  # type: builtin___int
    parallelism = ...  # type: builtin___int
    image = ...  # type: typing___Text
    @property
    def resources(self) -> global___Resources: ...
    def __init__(
        self,
        *,
        name: typing___Optional[typing___Text] = None,
        num_tasks: typing___Optional[builtin___int] = None,
        parallelism: typing___Optional[builtin___int] = None,
        image: typing___Optional[typing___Text] = None,
        resources: typing___Optional[global___Resources] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> JobSpec: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> JobSpec: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(
        self, field_name: typing_extensions___Literal["resources", b"resources"]
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "image",
            b"image",
            "name",
            b"name",
            "num_tasks",
            b"num_tasks",
            "parallelism",
            b"parallelism",
            "resources",
            b"resources",
        ],
    ) -> None: ...

global___JobSpec = JobSpec

class Resources(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    cpus = ...  # type: typing___Text
    mem = ...  # type: typing___Text
    def __init__(
        self,
        *,
        cpus: typing___Optional[typing___Text] = None,
        mem: typing___Optional[typing___Text] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Resources: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> Resources: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["cpus", b"cpus", "mem", b"mem"]
    ) -> None: ...

global___Resources = Resources

class TaskSpec(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    task_id = ...  # type: typing___Text
    command = ...  # type: typing___Text
    retries = ...  # type: builtin___int
    raw_data = ...  # type: builtin___bytes
    @property
    def data(self) -> global___TaskData: ...
    def __init__(
        self,
        *,
        task_id: typing___Optional[typing___Text] = None,
        data: typing___Optional[global___TaskData] = None,
        command: typing___Optional[typing___Text] = None,
        retries: typing___Optional[builtin___int] = None,
        raw_data: typing___Optional[builtin___bytes] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> TaskSpec: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> TaskSpec: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(
        self, field_name: typing_extensions___Literal["data", b"data"]
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "command",
            b"command",
            "data",
            b"data",
            "raw_data",
            b"raw_data",
            "retries",
            b"retries",
            "task_id",
            b"task_id",
        ],
    ) -> None: ...

global___TaskSpec = TaskSpec

class JobItem(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def job_spec(self) -> global___JobSpec: ...
    @property
    def task_spec(self) -> global___TaskSpec: ...
    def __init__(
        self,
        *,
        job_spec: typing___Optional[global___JobSpec] = None,
        task_spec: typing___Optional[global___TaskSpec] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> JobItem: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> JobItem: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "item", b"item", "job_spec", b"job_spec", "task_spec", b"task_spec"
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "item", b"item", "job_spec", b"job_spec", "task_spec", b"task_spec"
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions___Literal["item", b"item"]
    ) -> typing_extensions___Literal["job_spec", "task_spec"]: ...

global___JobItem = JobItem

class TaskData(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    input = ...  # type: typing___Text
    output = ...  # type: typing___Text
    def __init__(
        self,
        *,
        input: typing___Optional[typing___Text] = None,
        output: typing___Optional[typing___Text] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> TaskData: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> TaskData: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal["input", b"input", "output", b"output"],
    ) -> None: ...

global___TaskData = TaskData

class ServerMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    msg = ...  # type: typing___Text
    def __init__(self, *, msg: typing___Optional[typing___Text] = None,) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ServerMessage: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> ServerMessage: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["msg", b"msg"]
    ) -> None: ...

global___ServerMessage = ServerMessage

class SubmitTaskResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def result(self) -> global___TaskResult: ...
    @property
    def msg(self) -> global___ServerMessage: ...
    @property
    def heartbeat(self) -> global___Heartbeat: ...
    def __init__(
        self,
        *,
        result: typing___Optional[global___TaskResult] = None,
        msg: typing___Optional[global___ServerMessage] = None,
        heartbeat: typing___Optional[global___Heartbeat] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> SubmitTaskResponse: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> SubmitTaskResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "heartbeat",
            b"heartbeat",
            "msg",
            b"msg",
            "response",
            b"response",
            "result",
            b"result",
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "heartbeat",
            b"heartbeat",
            "msg",
            b"msg",
            "response",
            b"response",
            "result",
            b"result",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions___Literal["response", b"response"]
    ) -> typing_extensions___Literal["result", "msg", "heartbeat"]: ...

global___SubmitTaskResponse = SubmitTaskResponse

class ExecResult(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Status(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> "ExecResult.Status": ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List["ExecResult.Status"]: ...
        @classmethod
        def items(
            cls,
        ) -> typing___List[typing___Tuple[builtin___str, "ExecResult.Status"]]: ...
        SUCCESS = typing___cast("ExecResult.Status", 0)
        FAIL = typing___cast("ExecResult.Status", 1)
    SUCCESS = typing___cast("ExecResult.Status", 0)
    FAIL = typing___cast("ExecResult.Status", 1)
    global___Status = Status

    status = ...  # type: global___ExecResult.Status
    err_msg = ...  # type: typing___Text
    def __init__(
        self,
        *,
        status: typing___Optional[global___ExecResult.Status] = None,
        err_msg: typing___Optional[typing___Text] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ExecResult: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> ExecResult: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "err_msg", b"err_msg", "status", b"status"
        ],
    ) -> None: ...

global___ExecResult = ExecResult

class TaskResult(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    exit_code = ...  # type: builtin___int
    job_id = ...  # type: typing___Text
    task_id = ...  # type: typing___Text
    stdout = ...  # type: typing___Text
    stderr = ...  # type: typing___Text
    data = ...  # type: builtin___bytes
    @property
    def exec_result(self) -> global___ExecResult: ...
    def __init__(
        self,
        *,
        exit_code: typing___Optional[builtin___int] = None,
        job_id: typing___Optional[typing___Text] = None,
        task_id: typing___Optional[typing___Text] = None,
        stdout: typing___Optional[typing___Text] = None,
        stderr: typing___Optional[typing___Text] = None,
        data: typing___Optional[builtin___bytes] = None,
        exec_result: typing___Optional[global___ExecResult] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> TaskResult: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> TaskResult: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(
        self, field_name: typing_extensions___Literal["exec_result", b"exec_result"]
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "data",
            b"data",
            "exec_result",
            b"exec_result",
            "exit_code",
            b"exit_code",
            "job_id",
            b"job_id",
            "stderr",
            b"stderr",
            "stdout",
            b"stdout",
            "task_id",
            b"task_id",
        ],
    ) -> None: ...

global___TaskResult = TaskResult

class TaskRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    job_id = ...  # type: typing___Text
    def __init__(self, *, job_id: typing___Optional[typing___Text] = None,) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> TaskRequest: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> TaskRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["job_id", b"job_id"]
    ) -> None: ...

global___TaskRequest = TaskRequest

class ExecutorInit(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    client_id = ...  # type: typing___Text
    def __init__(
        self, *, client_id: typing___Optional[typing___Text] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ExecutorInit: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> ExecutorInit: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["client_id", b"client_id"]
    ) -> None: ...

global___ExecutorInit = ExecutorInit

class ExecutorRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def task_result(self) -> global___TaskResult: ...
    @property
    def task_request(self) -> global___TaskRequest: ...
    @property
    def executor_init(self) -> global___ExecutorInit: ...
    @property
    def heartbeat(self) -> global___Heartbeat: ...
    def __init__(
        self,
        *,
        task_result: typing___Optional[global___TaskResult] = None,
        task_request: typing___Optional[global___TaskRequest] = None,
        executor_init: typing___Optional[global___ExecutorInit] = None,
        heartbeat: typing___Optional[global___Heartbeat] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ExecutorRequest: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> ExecutorRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "action",
            b"action",
            "executor_init",
            b"executor_init",
            "heartbeat",
            b"heartbeat",
            "task_request",
            b"task_request",
            "task_result",
            b"task_result",
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "action",
            b"action",
            "executor_init",
            b"executor_init",
            "heartbeat",
            b"heartbeat",
            "task_request",
            b"task_request",
            "task_result",
            b"task_result",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions___Literal["action", b"action"]
    ) -> typing_extensions___Literal[
        "task_result", "task_request", "executor_init", "heartbeat"
    ]: ...

global___ExecutorRequest = ExecutorRequest

class Heartbeat(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    def __init__(self,) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Heartbeat: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> Heartbeat: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

global___Heartbeat = Heartbeat

class Shutdown(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    def __init__(self,) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Shutdown: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> Shutdown: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

global___Shutdown = Shutdown

class ExecutorResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def task_spec(self) -> global___TaskSpec: ...
    @property
    def heartbeat(self) -> global___Heartbeat: ...
    @property
    def shutdown(self) -> global___Shutdown: ...
    def __init__(
        self,
        *,
        task_spec: typing___Optional[global___TaskSpec] = None,
        heartbeat: typing___Optional[global___Heartbeat] = None,
        shutdown: typing___Optional[global___Shutdown] = None,
    ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ExecutorResponse: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> ExecutorResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "heartbeat",
            b"heartbeat",
            "response",
            b"response",
            "shutdown",
            b"shutdown",
            "task_spec",
            b"task_spec",
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "heartbeat",
            b"heartbeat",
            "response",
            b"response",
            "shutdown",
            b"shutdown",
            "task_spec",
            b"task_spec",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions___Literal["response", b"response"]
    ) -> typing_extensions___Literal["task_spec", "heartbeat", "shutdown"]: ...

global___ExecutorResponse = ExecutorResponse
